version: "3.9"
services:
  app:
    image: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgres://postgres:${DB_PASSWORD}@postgres:5432/nextjs_app
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - volume:/app/uploads
    container_name: nextjs-app
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nextjs_app
    ports:
      - "5432:5432"
    volumes:
      - volume:/var/lib/postgresql/data
volumes:
  volume:
    name: nextjs-app