import AdminNavigation from "@/components/admin/admin-navigation";
import Navbar from "@/components/navbar";
import { SessionProvider } from "@/components/providers/session-provider";
import { requireAuth } from "@/lib/auth/session";
import { APP_TITLE } from "@/lib/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: `Admin | ${APP_TITLE}`,
    description: "Generated by create next app"
};

export default async function AdminLayout({children}: Readonly<{children: React.ReactNode}>) {
    const {user, session} = await requireAuth("admin:access");

    return(
        <SessionProvider value={{user, session}}>
            <Navbar showUser/>
            <main className="w-full max-w-350 mx-auto flex gap-10 px-2 sm:px-4 my-10">
                <AdminNavigation/>
                {children}
            </main>
        </SessionProvider>
    );
}